version: '3.3'
services:
# Change if we're not using mongo. Also need to change the wait_hosts
# The wait_hosts is the default port for mongo
  mongo:
    image: mongo:4.2.5
#   db:
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_DATABASE: 'db'
#       # So you don't have to use root, but you can if you like
#       MYSQL_USER: 'user'
#       # You can use whatever password you like
#       MYSQL_PASSWORD: 'password'
#       # Password for root access
#       MYSQL_ROOT_PASSWORD: 'password'
#     ports:
#       # <Port exposed> : < MySQL Port running inside container>
#       - '3306:3306'
#     expose:
#       # Opens port 3306 on the container
#       - '3306'
#       # Where our data will be persisted
#     volumes:
#       - my-db:/var/lib/mysql
# # Names our volume
# volumes:
#   my-db:
main:
  build: .
  environment:
    # Need to add our defaul mySQL port to line below
    WAIT_HOTS: mongo:27017
#  environment:
#    WAIT_HOSTS: mongo:27017
  # Sometime a port doesn't work. Try "- '3306:3306'". And if you do, also change expose port
  # Left one is port outside of container, the right one is the port inside the container
  ports:
    - '8080:8080'
